# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=200)),
                ('Apeidos', models.CharField(max_length=200)),
                ('Edad', models.CharField(max_length=200)),
                ('Peso', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
