# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20170522_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='meta',
            field=models.CharField(choices=[('A', 'Aumentar'), ('B', 'Bajar')], default='B', max_length=1),
        ),
    ]
