# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20170314_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
